- name: Install supervisor
  dnf:
    name: supervisor
    state: present

- name: Ensure custom taks configuration exists
  template:
    src: "{{ mageops_project_templates_dir }}/{{ item.src }}"
    dest: "/etc/supervisord.d/{{ item.name }}.ini"
  with_items: "{{ supervisor_programs }}"
  when: supervisor_programs | length > 0
  notify: Reload supervisord

- name: Ensure Supervisor systemd config override directory exists
  file:
    path: /etc/systemd/system/supervisord.service.d/
    state: directory

- name: Create systemd service file for supervisord
  template:
    src: supervisord.overrides.conf
    dest: /etc/systemd/system/supervisord.service.d/mageops.conf

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start supervisord
  systemd:
    name: supervisord
    enabled: "{{ supervisor_service_autostart }}"
    state: "{{ supervisor_service_initial_state }}"

- name: Force a restart if configuration has changed
  meta: flush_handlers


